<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>w</string>
		<string>html</string>
	</array>
	<key>name</key>
	<string>HTML (ABL)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>.*(&lt;)(script) (language)(=)("SpeedScript")(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.inline.any.html</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.double.quoted.html</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>.*(&lt;/)(script)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.abl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.abl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.abl</string>
	<key>uuid</key>
	<string>043f4cd2-a6ba-49fc-b269-0fbf41acb7e5</string>
</dict>
</plist>
